- name: configure Db server
  hosts: db
  become: yes
  vars:
      login_host: db.nsrinformation.cloud
  vars_prompt:
    - name: mysql_root_password
      prompt: please enter password
      private: no
  tasks:
  - name: mysql server install
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: install mysql dependencies
    ansible.builtin.pip:
    - PyMySQL
    - cryptography
    executable: pip3.9
 
  - name: check db connection
    community.mysql.mysql_info:
      login_user: root  
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output
  
  - name: print output
    ansible.builtin.debug:
      msg: "Output: {{ mysql_connection_output }}"

  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_connection_output. failed is true 
    

